version: '3.8'

services:
  mailforge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailforge_server
    network_mode: host
    volumes:
      - .:/app
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: mailforge_dashboard
    network_mode: host
    volumes:
      - .:/app
    depends_on:
      - mailforge
    restart: unless-stopped
